[![Open All Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/analytics-club-iitm/DL-Marathon/blob/main/intro/pytorch_intro.ipynb)

In [1]:
# importing pytorch
import torch

/opt/miniconda3/envs/torch-nightly/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# creating a tensor

# zero tensor
zeros = torch.zeros(5)
print(zeros)
# ones
ones = torch.ones(5)
print(ones)
# random normal
random = torch.randn(5)
print(random)

tensor([0., 0., 0., 0., 0.])
tensor([1., 1., 1., 1., 1.])
tensor([-0.9226, -0.4759, -0.8283, -0.0429, -0.2678])


In [3]:
# multi dimenstional tensors

# 2D
two_dim = torch.randn((3, 3))
print(two_dim)
# 3D 
three_dim = torch.randn((3, 3, 3))
print(three_dim)

tensor([[-0.7086,  0.5833, -0.6784],
        [ 0.0612,  0.2426,  0.0216],
        [-0.2069,  0.6905, -1.2957]])
tensor([[[-0.2458, -1.7286,  0.1315],
         [ 0.5496, -0.0911,  0.1577],
         [ 0.2738,  2.0827,  0.0027]],

        [[ 1.5192, -0.0942, -0.0751],
         [ 0.1414, -0.1927,  1.0638],
         [-0.5661, -0.2539,  0.4815]],

        [[ 0.2348, -1.2164, -1.5791],
         [-1.2979, -0.4811, -1.1629],
         [-1.3320,  0.9052,  1.1341]]])


In [4]:
# tensor shapes and axes

print(zeros.shape)
print(two_dim.shape)
print(three_dim.shape)

# zeroth axis - rows
print(two_dim[:, 0])
# first axis - columns
print(two_dim[0, :])

torch.Size([5])
torch.Size([3, 3])
torch.Size([3, 3, 3])
tensor([-0.7086,  0.0612, -0.2069])
tensor([-0.7086,  0.5833, -0.6784])


In [5]:
# some other operations

# reshape
a = torch.randn((3, 4))
print(a)
a_reshaped = a.view(2, 6)
print(a_reshaped)

# reshape with -1
a_reshaped = a.view(4, -1)
a_reshaped = a.view(-1)

# max, mean
val = torch.max(a)
print(val)
a_mean = torch.mean(a)
print(a_mean)

# along various axes
val, ind = torch.max(a, dim=0)
print(val, ind)
val, ind = torch.max(a, dim=1)
print(val, ind)

tensor([[ 2.3502, -2.2359,  0.3922, -1.3882],
        [-0.0369, -0.3794,  0.0401,  0.1474],
        [-1.3354, -0.1249, -0.4322,  0.1471]])
tensor([[ 2.3502, -2.2359,  0.3922, -1.3882, -0.0369, -0.3794],
        [ 0.0401,  0.1474, -1.3354, -0.1249, -0.4322,  0.1471]])
tensor(2.3502)
tensor(-0.2380)
tensor([ 2.3502, -0.1249,  0.3922,  0.1474]) tensor([0, 2, 0, 1])
tensor([2.3502, 0.1474, 0.1471]) tensor([0, 3, 3])


In [9]:
# cpu-gpu
a = torch.randn((3, 4))
print(a.device)

device = torch.device("cuda")
a = a.to(device)
print(a.device)

# a more generic code
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

cpu
mps:0


In [10]:
# torch to numpy

a = a.cpu().numpy()
print(type(a))

# numpy to torch
import numpy as np
a = np.ones((3, 3))
a = torch.from_numpy(a)
print(type(a))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [11]:
# basic back prop

# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)    # x.grad = 2 (w)
print(w.grad)    # w.grad = 1 (x)
print(b.grad)    # b.grad = 1 (1)

tensor(2.)
tensor(1.)
tensor(1.)


In [12]:
# defining layers

import torch.nn as nn

layer1 = nn.Linear(3, 3)
print(layer1)

Linear(in_features=3, out_features=3, bias=True)


In [13]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())

# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

# 1-step gradient descent.
optimizer.step()

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())

w:  Parameter containing:
tensor([[ 0.2669,  0.3833,  0.0285],
        [-0.4717, -0.1962,  0.1754]], requires_grad=True)
b:  Parameter containing:
tensor([0.2469, 0.0240], requires_grad=True)
loss:  0.6296709775924683
dL/dw:  tensor([[ 0.5352,  0.3971, -0.3497],
        [-0.3591,  0.0276,  0.2815]])
dL/db:  tensor([-0.4149,  0.1274])
loss after 1 step optimization:  0.6201015114784241


In [14]:
from torchvision import datasets, transforms

# use existing datasets
# Download and construct CIFAR-10 dataset.
val_dataset = datasets.CIFAR10(
    root='./data/', 
    train=False, 
    transform=transforms.ToTensor(), 
    download=True
)

# Fetch one data pair (read data from disk).
image, label = val_dataset[10]
import matplotlib.pyplot as plt
plt.imshow(image.permute(1, 2, 0).numpy())
plt.show()
print(image.shape)
print(label)

  7%|▋         | 11993088/170498071 [00:19<04:21, 607132.23it/s] 


KeyboardInterrupt: 

In [ ]:
from torch.utils.data import DataLoader
# Data loader (this provides queues and threads in a very simple way).
loader = torch.utils.data.DataLoader(
    dataset=val_dataset,
    batch_size=64, 
    shuffle=True
)

# how data is loaded in the backend
# When iteration starts, queue and thread start to load data from files.
data_iter = iter(loader)
# Mini-batch images and labels.
images, labels = data_iter.next()
print(images.shape, labels.shape)

# Usage of the data loader is as below.
for images, labels in loader:
    # Training code should be written here.
    print(images.shape, labels.shape)
    break

torch.Size([64, 3, 32, 32]) torch.Size([64])
torch.Size([64, 3, 32, 32]) torch.Size([64])


In [ ]:
from torch.utils.data import Dataset

# Defining a custom dataset
class CustomDataset(Dataset):
    def __init__(self):
        # 1. Initialize file paths or a list of file names. 
        pass
    def __getitem__(self, index):
        # 1. Read one data from file (e.g. using numpy.fromfile, PIL.Image.open).
        # 2. Preprocess the data (e.g. torchvision.Transform).
        # 3. Return a data pair (e.g. image and label).
        return None
    def __len__(self):
        # return length of the dataset
        return 0 # here 0 because there are no elements

# You can then use the prebuilt data loader. 
custom_dataset = CustomDataset()
custom_loader = torch.utils.data.DataLoader(
    dataset=custom_dataset,
    batch_size=64, 
    shuffle=True
)

In [ ]:
# defining models

class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()
        # 1. initialize all the model layers (eg: nn.Linear(), nn.Conv2d(),etc)
        self.layer1 = nn.Linear(3, 3)

    def forward(self, inp):
        # 1. pass through the required layers and perform the necessary operations
        # eg: out = self.layer1(x)
        # return final output
        out = self.layer1(inp)
        return out

model = CustomModel().to(device)
inp = torch.randn((2, 3)).to(device)
output = model(inp)
print(output)

tensor([[0.4268, 0.4466, 0.0190],
        [0.6959, 0.7932, 0.0326]], device='cuda:0', grad_fn=<AddmmBackward>)


In [ ]:
# Save and load the entire model.
torch.save(model.state_dict(), 'model.ckpt')
model.load_state_dict(torch.load('model.ckpt'))

<All keys matched successfully>

## Linear regression (EXTREME OVERKILL CODE)

In [15]:
# SUPER UNWANTEDLY LARGE LINEAR REGRESSION CODE (HOWEVER WILL GIVE U AN OVERALL IDEA SO YEAH)

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt


class XYSet(Dataset):
    def __init__(self):
        # toy dataset
        data = np.genfromtxt("https://raw.githubusercontent.com/MukundVarmaT/PythonMLworkshop/master/data.csv", delimiter=",")
        self.x, self.y = data[:,[0]], data[:, [1]]
    def __getitem__(self, indx):
        return self.x[indx], self.y[indx]
    def __len__(self):
        return len(self.x)


class LinReg(nn.Module):
    def __init__(self):
        super(LinReg, self).__init__()
        self.layer = nn.Linear(1, 1)
    def forward(self, x):
        return self.layer(x)

dset = XYSet()
loader = DataLoader(dset, batch_size=8, num_workers=4)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = LinReg().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.0001)
criterion = nn.MSELoss()

# Train the model
for epoch in range(200):
    loss_cntr = []
    for x, y in loader:
        x, y = x.to(device).float(), y.to(device).float()
        y_pred = model(x)
        loss = criterion(y_pred, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        loss_cntr.append(loss.item())
    if epoch % 10 == 0:
        print ('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, 200, np.mean(loss_cntr)))

# Plot the graph
predicted = model(torch.from_numpy(dset.x).to(device).float()).cpu().detach().numpy()
plt.plot(dset.x, dset.y, 'ro', label='Original data')
plt.plot(dset.x, predicted, label='Fitted line')
plt.legend()
plt.show()

# Save the model checkpoint
torch.save(model.state_dict(), 'model.ckpt')


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/torch-nightly/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/miniconda3/envs/torch-nightly/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'XYSet' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/torch-nightly/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/miniconda3/envs/torch-nightly/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'XYSet' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/

RuntimeError: DataLoader worker (pid(s) 6444) exited unexpectedly